trigger:
- main  # Change this to your branch name

pool:
  vmImage: 'ubuntu-latest'  # Use an appropriate VM image

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'  # Specify your Node.js version
  displayName: 'Install Node.js'

- script: |
    npm install  # Install dependencies
    npx playwright install  # Install Playwright browsers
  displayName: 'Install dependencies'

- script: |
    npx playwright test  # Run your Playwright tests
  displayName: 'Run Playwright tests'
