trigger:
- main  # Change to your default branch

pool:
  vmImage: 'ubuntu-latest'  # Use Ubuntu image

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'  # Specify the Node.js version
  displayName: 'Install Node.js'

- script: |
    npm install
    npx playwright install
  displayName: 'Install dependencies and browsers'

- script: npm test  # Runs the Playwright tests
  displayName: 'Run Playwright tests'

